---
- hosts: default
  become: true
  gather_facts: false

  tasks:
  - name: Update and upgrade apt packages
    ansible.builtin.apt:
      upgrade: true
      update_cache: true

  - name: Remove dependencies that are no longer required
    ansible.builtin.apt:
      autoremove: true

  - name: Clean apt repository
    ansible.builtin.command: apt clean
    changed_when: false

  - name: Truncate machine-id
    community.general.filesize:
      path: /etc/machine-id
      size: 0

  - name: Remove network config
    ansible.builtin.file:
      path: /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
      state: absent

  - name: Remove netplan installer config
    ansible.builtin.file:
      path: /etc/netplan/00-installer-config.yaml
      state: absent

  - name: Remove netplan cloud-init config
    ansible.builtin.file:
      path: /etc/netplan/50-cloud-init.yaml
      state: absent

  - name: Create PVE cloud config
    ansible.builtin.template:
      src: 99_pve.cfg.j2
      dest: /etc/cloud/cloud.cfg.d/99_pve.cfg
      mode: 0644

  - name: Cloud-Init clean
    ansible.builtin.command: cloud-init clean --logs
    changed_when: true
